# Introduction

Welcome to the AnVIL Getting Started guide!  In it you will find step-by-step instructions for setting up your accounts, as well as guides on how to use some of AnVIL’s key features.

### What Is AnVIL?

AnVIL is NHGRI's Genomic Data Science Analysis, Visualization, and Informatics Lab-space.  It provides a platform for performing genomic data analysis on the cloud.

#### Does AnVIL Cost Money?

Through AnVIL, you pay for computing resources as you use them.  If you'd like to try it out, new users can claim a $300 Google Cloud credit to test out the platform and perform some small analyses.

We also provide a [cost estimator](budget-templates.html#types-of-costs).

#### Where Can I Get Help?

Please visit our community support forum at [`help.anvilproject.org`](https://help.anvilproject.org) with any questions (or suggestions!) you may have.

Also join the AnVIL Mailing List `anvil-mailing-list@lists.anvilproject.org` by subscribing here: [https://lists.anvilproject.org/lists/anvil-mailing-list.lists.anvilproject.org/]([https://lists.anvilproject.org/lists/anvil-mailing-list.lists.anvilproject.org/).

#### AnVIL Collection

Additional guides are provided to help you with Workspaces, launch interactive tools, and start working with data. Learn more about AnVIL by visiting https://anvilproject.org or reading the [article in Cell Genomics](https://www.sciencedirect.com/science/article/pii/S2666979X21001063).

Please check out our full collection of AnVIL and related resources: https://hutchdatascience.org/AnVIL_Collection/

### Why AnVIL?

<iframe width="560" height="315" src="https://www.youtube.com/embed/XC5qzj-yZb8" title="YouTube video player" frameborder="0" allow="accelerometer; autoplay; clipboard-write; encrypted-media; gyroscope; picture-in-picture" allowfullscreen></iframe>

Read on for more information regarding "Why use the AnVIL?" in the next chapter, or skip ahead to another guide.

```{r echo=FALSE, results = 'asis'}
cow::borrow_chapter("why-anvil-overview.Rmd",
                    repo_name = "jhudsl/AnVIL_Template")

```
