# Consortia

This chapter is targeted towards people who are part of a consortium and plan to use AnVIL as part of their activities. You will find here:

<br>
<!-- The capital letter above alters the formatting for the bullet points below -->

- **Account Setup Overview** -- Goals for this guide and help choosing a role in the consortium
- **Account Setup Steps** -- Step-by-step instructions to create your first accounts as part of the consortium on AnVIL

::: {.fyi}
Please click on the subsection headers in the left hand 
navigation bar (e.g., 2.2, 4.2) a second time to expand the 
table of contents and enable the `scroll_highlight` feature 
([see more](introduction.html#scroll-highlight)).
:::

## Account Setup Overview {#overview-consortia}

### Goals for This Guide

```{r, echo=FALSE, fig.alt="List of goals for this guide: 1) Choose your consortium role, 2) Get your accounts, and 3) Link external accounts."}
leanbuild::include_slide("https://docs.google.com/presentation/d/1dOubh-sTo5K3okZXx_7OVvUaRO58UzDn7w-pWwHD8CE/edit#slide=id.gd5c49c5c55_0_165")
```

### Choosing a Role

Consortia are usually made up of scientists taking on different research roles. This guide will be most helpful to you if you target the section most closely related to your role. The sections are summarized by role below:

**Data Manager**

The data manager is responsible for controlling access of consortium members. To protect data security, data managers ensure that consortium members only have access to appropriate datasets. If there are multiple datasets, the data manager will manage consortium member access as appropriate to a subset of those datasets. These limited access permissions are organized via distinct [Terra Authorization Domains](auth-domains.html).

**Principal Investigator / Lab Manager**

PIs are responsible for managing billing expenses accrued by members of the consortium. Within the consortium, PIs can add members to [Workspaces](workspaces.html) managed under specific Google Billing Accounts and Billing Projects, providing centralized control over computing and data storage expenses. Principal investigators will need to work with data managers to ensure their team members have correct data access via [Terra Authorization Domains](auth-domains.html), where necessary.

**Data Analyst / Researcher**

A consortium data analyst might describe someone who is performing analyses or writing code, but isn't responsible for managing dataset access or billing expenses. The Analyst should be able to identify the PI or data manager point of contact in the consortium. Analysts will not be able to run analyses or access data without explicit permission from consortium management. This role also describes research leaders who will participate in activities but will not be managing personnel or expenses as part of the consortium.

**Data Submitter**

Data submitters are responsible for working with the AnVIL Data Ingestion Team as well as the National Center for Biotechnology Information (NCBI) to make data available on AnVIL. Data submitters will work with the data manager to ensure the data is protected via the appropriate [Terra Authorization Domains](auth-domains.html).

### Draft Security Policies

Consortia leadership are responsible for the following:

- Drafting Memorandums of Understanding (MOUs) and Data Use Agreements (DUAs)
- Arranging IRB oversight
- Drafting policy and protocol for data security and management incidents
- Ensuring all consortium members are aware of all data use limitations and the terms of the consortium agreements
- Defining what it means to be a consortium member
- Developing clear timelines and milestones for sharing data with the community rapidly, completely, and in NIH-designated data repositories
- Creating a timeline for closing out the consortium and thus the consortium-managed, streamlined access for consortium members
- Communicating the timeline with relevant NHGRI program staff and provide AnVIL with 6 months' notice of when the consortium's data access is expected to end

## Consortium Data Managers

### Managing Security and Privacy Policies

As a data manager, you are responsible for managing access to sensitive data. You should be involved in managing the following:  

- Drafting Memorandums of Understanding (MOUs) and Data Use Agreements (DUAs)  
- Arranging and managing IRB oversight  
- Drafting policy and protocol for reporting data security and management incidents  
- Managing data use limitations and conditions of consortium membership  

### Account Setup

To set up your account on AnVIL, please see the section for [PIs and lab managers](pis-and-lab-managers.html#overview-pis).

### Two Factor Authentication

Note that you must establish [two factor authentication](https://support.google.com/accounts/answer/185839?co=GENIE.Platform%3DDesktop&hl=en) on your Google Account for added security. 

### Set Up Terra Authorization Domains

Terra Authorization Domains help keep sensitive genomic data secure while still allowing easy sharing with collaborators. See the Security section on [Terra Authorization Domains](auth-domains.html) for more information on setting up these secure access groups.

### Granting Access

Data managers should confirm that **all other consortium members** have two factor authentication set up on their Google accounts prior to granting access to datasets. 

Granting member access to datasets should be controlled via [Terra Authorization Domains](auth-domains.html).

### Revoking Access

Revoking access to datasets, either when a member leaves the consortium or the consortium concludes, should be controlled via [Terra Authorization Domains](auth-domains.html).

## Consortium PIs and Lab Managers

### Be Aware of Security Policies

As part of a consortium on AnVIL, you should be aware of the following:
- Memorandums of Understanding (MOUs) and Data Use Agreements (DUAs)
- IRB oversight of the consortium
- Policy and protocol for reporting data security and management incidents

### Account Setup

To set up your account on AnVIL, please see the section for [PIs and lab managers](pis-and-lab-managers.html#overview-pis).

### Two Factor Authentication

Note that you must establish [two factor authentication](https://support.google.com/accounts/answer/185839?co=GENIE.Platform%3DDesktop&hl=en) on your Google Account for added security.

## Consortium Data Analysts and Researchers

### Be Aware of Security Policies

As part of a consortium on AnVIL, you should be aware of the following:
- Memorandums of Understanding (MOUs) and Data Use Agreements (DUAs)
- IRB oversight of the consortium
- Policy and protocol for reporting data security and management incidents

### Account Setup

To set up your account on AnVIL, please see the section for [data analysts](data-analysts.html#overview-analysts).

### Two Factor Authentication

Note that you must establish [two factor authentication](https://support.google.com/accounts/answer/185839?co=GENIE.Platform%3DDesktop&hl=en) on your Google Account for added security.

## Consortium Data Submitters

### Be Aware of Security Policies

As part of a consortium on AnVIL, you should be aware of the following:
- Memorandums of Understanding (MOUs) and Data Use Agreements (DUAs)
- IRB oversight of the consortium
- Policy and protocol for reporting data security and management incidents

### Account Setup

To set up your account on AnVIL, please see the section for [data submitters](https://anvilproject.org/learn/data-submitters/submission-guide/data-submitters-overview).

### Two Factor Authentication

Note that you must establish [two factor authentication](https://support.google.com/accounts/answer/185839?co=GENIE.Platform%3DDesktop&hl=en) on your Google Account for added security.

## Wrap-Up {#consortia-wrap-up}

**Congratulations! You have successfully set up your AnVIL account!**

You should now be able to move forward with your consortium activities, such as adding personnel to appropriate datasets or working in a Workspace. Remember that you will need to coordinate with other members of the consortium to establish appropriate permissions for datasets, Terra Billing Projects, and Workspaces.
