# Instructors

This chapter is targeted towards people who are teaching a course or workshop on AnVIL. You will find here:

<br> <!-- Capital letter makes part of below content indented which doesn't look good.. can remove the <br> if more text is added above -->
<br>

- **Overview** -- Design philosophy and goals for this guide - is this a good fit for your class?  What should you know before you start?
- **Account Setup** -- Step-by-step instructions to create your first accounts on AnVIL and create your first class Workspace
- **Developing Content** -- Additional tools to help you customize your class Workspace
- **Class Setup** -- Step-by-step instructions to help you add students into a class on AnVIL
- **Class Ending** -- Best practices for finishing your course cleanly and minimizing costs
- **Student Account Setup** -- Step-by-step account set up for students using AnVIL in your class

::: {.fyi}
Please click on the subsection headers in the left hand 
navigation bar (e.g., 2.2, 4.2) a second time to expand the 
table of contents and enable the `scroll_highlight` feature 
([see more](https://jhudatascience.org/AnVIL_Book_Getting_Started/introduction.html#activate-scroll_highlight-feature)).
:::

<!------------------------------------------>

## Overview

### Goals for This Guide

```{r, echo=FALSE, fig.alt="List of goals for this guide: (1) get your accounts, (2) set up billing, (3) create your first Workspace, (4) develop content, and (5) set up classes with students."}
leanbuild::include_slide("https://docs.google.com/presentation/d/1HHWg47Tg6miv_K7GNB6ZDTx-4Jc5IMl7APfFtD1Rqag/edit#slide=id.ge21c626cf0_0_5")
```

### Design Philosophy

This guide provides an opinionated walkthrough on how to set up AnVIL for your class.  These step-by-step instructions take instructors that are completely new to the AnVIL through account setup to the point where you can feel comfortable hosting a class from start-to-finish on AnVIL. Following the recommendations in this guide will help you minimize expenses, develop content programmatically, track individual student expenses, and stop billing expenses from accruing once the class is complete. In support of these goals we have made the following design decisions:

1. ACCOUNT SETUP

a. Sign up for a personal Google Cloud Account, where you can get started by claiming [$300 free Google credits](https://cloud.google.com/free/docs/gcp-free-tier/#free-trial).

2. CONTENT DEVELOPING

a. Include version control and visibility of course content by using GitHub. This will allow you to add content programmatically, keep track of changes, and share your content with others outside of AnVIL.

3. CLASS SETUP

a. Create a separate Google Billing Account for each class. This will allow you to easily shut down expenses at the end of the class.
b. Choose one funding source per class (for example, the [STRIDES](#strides-funding) Program).
b. Create separate Terra Billing Projects for each student. This will allow you to monitor billing expenses closely and work with students to build best computing practices.

### Before You Start

- You will need a **credit card or bank account** to activate your free trial and get started. Don't worry! **You won't be billed until you explicitly turn on automatic billing**, but payment information is needed for verification purposes.
- Before setting up billing yourself, you may want to check with your institutional procurement office and see if they have a preferred account set-up method with Google (such as a third party reseller or an existing account).

<!-- Checklist -->

<!------------------------------------------>

## Account Setup

::: {.fyi}
Please click on the subsection headers in the left hand 
navigation bar (e.g., 2.2, 4.2) a second time to expand the 
table of contents and enable the `scroll_highlight` feature 
([see more](https://jhudatascience.org/AnVIL_Book_Getting_Started/introduction.html#activate-scroll_highlight-feature)).
:::

### Overview of Account Setup

### Step 1: Create a Google Account

### Step 2: Set Up Google Billing

### Step 3: Add Terra to Google Billing Account

### Step 4: Create a Terra Billing Project

### Step 5: Set Up Alerts

### Step 6: Create First Workspace

### Wrap-Up

<!------------------------------------------>

## Developing Content

### Overview

### Setup AnVILPublish Using AnVIL

### Update Dashboard

### Post Jupyter Notebook

<!------------------------------------------>

## Class Setup

### Identify Funding

#### NHGRI STRIDES {#strides-funding}

Through the [STRIDES](https://datascience.nih.gov/strides) program, NHGRI makes funding available to new users of the AnVIL, in collaboration with the [NIH Office of Data Science Strategy](https://datascience.nih.gov/about/odss). NHGRI currently supports the [AnVIL Cloud Credits Program (AC2)](https://anvilproject.org/news/2021/04/12/announcing-anvil-cloud-cost-credits-program) and will have a second round of funding available in fall of 2021.

### Set Up Billing Project

### Collect Student IDs

### Set Up Permissions

#### Add students as “Member” 

<!-- to Terra Group (so don’t have to type every ID) -->

#### Add Group as “Reader” 

<!-- to Instructor Workspace (to allow clone of this workspace) -->

#### Add Group as “User” 

<!-- Roles on Billing Project (allow to clone any workspace) -->

<!------------------------------------------>

## Class Ending

### Notify Students

### Disable Billing

<!------------------------------------------>

## Student Account Setup

### Create a Google Account

### Set Up Terra

### Provide ID to Instructor

<!------------------------------------------>

## Class Checklist

This checklist can serve as a reminder of the overall suggested steps to make a new class on AnVIL. You might find yourself changing these steps slightly as you become more familiar with AnVIL.

**Billing**
- Obtain funding through the [STRIDES](https://datascience.nih.gov/strides) program (optional)
- Request students make AnVIL IDs (Google IDs) 
- Collect AnVIL IDs (Google IDs) from students
- Create Google Billing Account for your class
- Create Terra Billing Projects for your students
- Deactivate Billing Projects

**Resources**
- Create a Workspace for your class
- Notify Terra of your course dates and times
- Direct students to the Workspace

**Permissions**
- Set up Groups to manage permissions

| AnVIL Group | Class Workspace | Terra Billing Projects*|
|-------------|-----------------|------------------------|
| Instructor  | Owner           | Owner                  |
| TAs         | Writer          | Owner                  |
| Students    | Reader          | User                   |

\* You should have n + 1 Terra Billing Projects: one for each student and one shared by instructors.
