# Tools

Four of the analysis platforms available on AnVIL include Jupyter Notebook, RStudio, Galaxy, and WDL Workflows.  Each tool offers a unique set of strengths such as accessible analysis reports incorporating multiple languages in the case of [Jupyter](https://anvilproject.org/learn/interactive-analysis/getting-started-with-jupyter-notebooks), rich genomics support through [Bioconductor](https://anvilproject.org/learn/interactive-analysis/getting-started-with-bioconductor) in the case of RStudio, a graphical interface for thousands of tools in the case of [Galaxy](https://anvilproject.org/learn/interactive-analysis/getting-started-with-galaxy), and extreme compute scalability in the case of WDL Workflows.  This chapter focuses on launching and highlighting a few features for the three interactive tools while a later chapter discusses [WDL Workflows](https://jhudatascience.org/AnVIL_Book_Getting_Started/workflows.html).

```{r, echo=FALSE}
leanbuild::include_slide( "https://docs.google.com/presentation/d/1_CXM3bVvauH6eahRg94zjC6fc6NGDrrnCt33jAABPRk/edit#slide=id.geb3ae37d4e_0_10" )
```

## Starting Jupyter Notebook

<iframe src="https://drive.google.com/file/d/1ZhPYFy4zuAHhPhF6T4pUgSReBmPJM-wg/preview" width="640" height="360" allow="autoplay"></iframe>

### Objectives

- Start compute for your Jupyter environment
- Create notebook to perform analysis
- Stop compute to minimize expenses

### Slides

The slides for this tutorial are are located [here](https://docs.google.com/presentation/d/1GYUP874Qd7K3S0Ls6iWY_M4jywpRb53qw0f78OBCFwk).

## Starting RStudio

<iframe src="https://drive.google.com/file/d/1v72ZG8JIRDUaewFQgGfcCO_qoM4eYmYX/preview" width="640" height="360" allow="autoplay"></iframe>

### Objectives

- Start compute for your RStudio environment
- Tour RStudio on AnVIL
- Stop compute to minimize expenses

### Slides

The slides for this tutorial are are located [here](https://docs.google.com/presentation/d/1eypYLLqD11-NwHLs4adGpcuSB07dYEJfAaALSMvgzqw).

## Starting Galaxy

<iframe src="https://drive.google.com/file/d/16QEY8x-gBsUkKEeO3w_H-I4SLIBPloXd/preview" width="640" height="360" allow="autoplay"></iframe>

### Objectives

- Start compute for your Galaxy on AnVIL
- Run tool to quality control sequencing reads
- Stop compute to minimize expenses

### Slides

The slides for this tutorial are are located [here](https://docs.google.com/presentation/d/1yYCg4cPVBMMDghT17B4XzROieqyMH99Ex9nMm_Scm9Q).
